apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plugin
rules:
- apiGroups:
  - sts.silicom.com
  resources:
  - stsnodes
  - stsnodes/status
  verbs:
  - get
  - list
  - update
  - create
  - delete
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
