
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - sts.silicom.com
  resources:
  - stsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sts.silicom.com
  resources:
  - stsconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - sts.silicom.com
  resources:
  - stsconfigs/status
  verbs:
  - get
  - patch
  - update
