# permissions for end users to view stsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stsconfig-viewer-role
rules:
- apiGroups:
  - sts.silicom.com
  resources:
  - stsconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sts.silicom.com
  resources:
  - stsconfigs/status
  verbs:
  - get
