# permissions for end users to edit stsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stsconfig-editor-role
rules:
- apiGroups:
  - sts.silicom.com
  resources:
  - stsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sts.silicom.com
  resources:
  - stsconfigs/status
  verbs:
  - get
