# permissions for end users to view stsdevicenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stsdevicenode-viewer-role
rules:
- apiGroups:
  - sts.silicom.com
  resources:
  - stsdevicenodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sts.silicom.com
  resources:
  - stsdevicenodes/status
  verbs:
  - get
