# permissions for end users to edit stsdevicenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stsdevicenode-editor-role
rules:
- apiGroups:
  - sts.silicom.com
  resources:
  - stsdevicenodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sts.silicom.com
  resources:
  - stsdevicenodes/status
  verbs:
  - get
