# permissions for end users to view stsnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stsnode-viewer-role
rules:
- apiGroups:
  - sts.silicom.com
  resources:
  - stsnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sts.silicom.com
  resources:
  - stsnodes/status
  verbs:
  - get
