---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plugin

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plugin
rules:
- apiGroups:
  - sts.silicom.com
  resources:
  - stsnodes
  - stsnodes/status
  verbs:
  - get
  - list
  - update
  - create
  - delete
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: plugin
subjects:
- kind: ServiceAccount
  name: plugin

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plugin
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plugin
subjects:
- kind: ServiceAccount
  name: plugin
roleRef:
  kind: ClusterRole
  name: plugin
  apiGroup: rbac.authorization.k8s.io
