apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tsync
rules:
- apiGroups:
  - sts.silicom.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged