apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "sts.silicom.com/v1alpha1",
          "kind": "StsConfig",
          "metadata": {
            "name": "bc-1",
            "namespace": "sts-silicom"
          },
          "spec": {
            "imageRegistry": "quay.io/silicom",
            "interfaces": [
              {
                "ethName": "enp2s0f0",
                "ethPort": 0,
                "holdoff": 500,
                "mode": "Slave",
                "synce": 1
              },
              {
                "ethName": "enp2s0f1",
                "ethPort": 1,
                "holdoff": 500,
                "mode": "Master",
                "synce": 1
              },
              {
                "ethName": "enp2s0f2",
                "ethPort": 2,
                "holdoff": 500,
                "mode": "Master",
                "synce": 1
              }
            ],
            "mode": "T-TBC.8275.1",
            "namespace": "sts-silicom",
            "nodeSelector": {
              "mode.sts.silicom.com/bc-1": "true"
            },
            "stsVersion": "2.0.1.0"
          }
        },
        {
          "apiVersion": "sts.silicom.com/v1alpha1",
          "kind": "StsConfig",
          "metadata": {
            "name": "gm-1",
            "namespace": "sts-silicom"
          },
          "spec": {
            "imageRegistry": "quay.io/silicom",
            "interfaces": [
              {
                "ethName": "enp2s0f0",
                "ethPort": 0,
                "holdoff": 500,
                "mode": "Master",
                "synce": 1
              },
              {
                "ethName": "enp2s0f1",
                "ethPort": 1,
                "holdoff": 500,
                "mode": "Master",
                "synce": 1
              }
            ],
            "mode": "T-GM.8275.1",
            "namespace": "sts-silicom",
            "nodeSelector": {
              "mode.sts.silicom.com/gm-1": "true"
            },
            "stsVersion": "2.0.1.0"
          }
        },
        {
          "apiVersion": "sts.silicom.com/v1alpha1",
          "kind": "StsNode",
          "metadata": {
            "name": "stsnode-sample"
          },
          "spec": {
            "foo": "bar"
          }
        }
      ]
    capabilities: Basic Install
    categories: OpenShift Optional
    containerImage: quay.io/silicom/siltsyncd
    description: Short description of the STS card
    repository: github.com/silicomdk/sts-operator
  name: sts-operator.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: StsConfig is the Schema for the stsconfigs API
      displayName: Sts Config
      kind: StsConfig
      name: stsconfigs.sts.silicom.com
      version: v1alpha1
    - description: StsNode is the Schema for the stsnodes API
      displayName: Sts Node
      kind: StsNode
      name: stsnodes.sts.silicom.com
      version: v1alpha1
  description: |
    Silicom STS line card for 4G and 5G NIC enable real-time data transmission
    with high timing accuracy at the lowest cost to power 5G DRAN and CRAN edge
    deployments.

    * Support 1588/PTP over IPv4 / IPV6, IEEE1588v2
    * Support SyncE /ITU-T G.8262
    * T-BC/T-TSC Boundary Clock and TSC Slave Clock /G.8273.2
    * T-GM Grand Master /G.8273.1 per G.8275.1 PTP Profile
    * PRTC Primary Reference Time Clock Class B/G.8272
    * T-TC Transparent Clock /G.8273.3
    * 1588 Software Stack and Servo Software in x86

    https://www.silicom-usa.com/pr/server-adapters/networking-adapters/10-gigabit-ethernet-networking-adapters/p410g8ts81-timesync-server-adapter/

    Details about the Operator
    Details the prerequisites for enabling the Operator
  displayName: sts-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sts
  - silicom
  - ptp
  links:
  - name: GitHub Repository
    url: https://github.com/silicomDK/sts-operator
  - name: Github SRO Helm Charts
    url: https://github.com/silicomDK/sts2-charts
  - name: Silicom Ltd.
    url: https://silicom.com
  maintainers:
  - email: rmr@silicom.dk
    name: Ryan M. Raasch
  maturity: alpha
  provider:
    name: Silicom Ltd.
    url: https://silicom.com
  version: 0.0.2
