apiVersion: sts.silicom.com/v1alpha1
kind: StsConfig
metadata:
  name: gmaster
spec:
  name: gmaster
  image: quay.io/ryan_raasch/siltsync:1.2.0.1
  podAnnotation:
    sts.silicom.com/mode-2: "asdf"
  nodeSelector:
    sts.silicom.com/mode-2: "saf"
  interfaces:
    - slot: 0
      function: 5
      up: true
      mode: 2
      synce: true
      holdoff: 500
    - slot: 0
      function: 0
      up: true
      mode: 2
      synce: true
      holdoff: 500
  cfg: |
    IPCServer = 1
    domainNum = 24
    forwardable = 0
    twoStep = 0
    priority2 = 128
    srcPPS = 1
    src10MHz = 1
    synceRecClkPort = 0
    syncOption = 1
    synceCpu = 10
    swTimestamp = 0
    inbandMode = 1 
    dumpMode = 0
    getRawTs = 0
    countDelay = 0
    dataDelay = 0
    statDelay = 0
    aprLevel = 8
    traceModule = 23
    traceLevel = 8
    tracePtpMsg = 0
    whenWriteLog = 0
    debugAPI = 1

  runCfg: |
    net_id=1591
    delay=10
    lane_map=8
    bcm_port_mask=0xff
    num_ports_10G=8
    num_ports_25G=4
