---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: sts-plugin
  namespace: {{.Namespace}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sts-plugin
  namespace: {{.Namespace}}
rules:
- apiGroups:
  - sts.silicom.com
  resources:
  - stsnodes
  - stsnodes/status
  verbs:
  - get
  - list
  - update
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sts-plugin
  namespace: {{.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sts-plugin
subjects:
- kind: ServiceAccount
  name: sts-plugin
  namespace: {{.Namespace}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sts-plugin
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sts-plugin
subjects:
- kind: ServiceAccount
  name: sts-plugin
  namespace: {{.Namespace}}
roleRef:
  kind: ClusterRole
  name: sts-plugin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: sts-plugin
  name: sts-plugin
  namespace: {{.Namespace}}
  annotations:
    openshift.io/scc: silicom-sts
spec:
  selector:
    matchLabels:
      app: sts-plugin
  template:
    metadata:
      labels:
        app: sts-plugin
    spec:
      nodeSelector:
        feature.node.kubernetes.io/custom-silicom.sts.devices: "true"
      serviceAccount: sts-plugin
      hostNetwork: true
      containers:
      - image: {{.ImageRegistry}}/sts-plugin:v0.0.1
        imagePullPolicy: Always
        name: sts-plugin-ctr
        securityContext:
          privileged: true
        env:
          - name: GPS_PORT
            value: "{{.GpsPort}}"
          - name: TSYNC_PORT
            value: "{{.TsyncPort}}"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - --zap-log-level=10
