---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Name}}
  namespace: {{.Spec.Namespace}}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{.Name}}
  namespace: {{.Spec.Namespace}}
rules:
- apiGroups:
  - sts.silicom.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Name}}
  namespace: {{.Spec.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{.Name}}
subjects:
- kind: ServiceAccount
  name: {{.Name}}
  namespace: {{.Spec.Namespace}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Name}}-siltsync-conf
  namespace: {{.Spec.Namespace}}
data:
  tsyncd.conf: |
    profileID = {{.ProfileId}}
{{ range $i, $dev := .Spec.Interfaces }}
    nicStr{{$i}} = {{$dev.EthName}}
    qlEnable{{$i}} = {{$dev.QlEnable}}
    holdOff{{$i}} = {{$dev.HoldOff}}
{{end}}
    slavePortMask = {{printf "0x%x" .SlavePortMask}}
    masterPortMask = {{printf "0x%x" .MasterPortMask}}
    syncePortMask = {{printf "0x%x" .SyncePortMask}}
    phyLedsCtl = {{.Spec.PhyLedsCtl}}
    IPCServer = 1
    domainNum = {{.Spec.DomainNumber}}
    forwardable = 0
    twoStep = 0
    priority2 = 128
    srcPPS = {{.Spec.SrcPPS}}
    src10MHz = {{.Spec.Src10MHz}}
    synceRecClkPort = {{.Spec.SynceRecClkPort}}
    syncOption = {{.Spec.SyncOption}}
    synceCpu = {{.Spec.SynceCpu}}
    swTimestamp = 0
    inbandMode = 1 
    dumpMode = 0
    getRawTs = 0
    countDelay = 0
    dataDelay = 0
    statDelay = 0
    aprLevel = 8
    traceModule = 23
    traceLevel = 8
    tracePtpMsg = 0
    whenWriteLog = 0
    debugAPI = 0

---

{{- if .EnableGPS }}
apiVersion: v1
kind: Service
metadata:
  name: {{.ServicePrefix}}-gpsd
  namespace: {{.Spec.Namespace}}
  labels:
    sts.silicom.com/svc: gpsd
spec:
  type: NodePort
  selector:
    app: {{.Name}}-{{.NodeName}}
  ports:
    - protocol: TCP
      port: 2947
      targetPort: 2947

---
{{end}}

apiVersion: v1
kind: Service
metadata:
  name: {{.ServicePrefix}}-tsyncd
  namespace: {{.Spec.Namespace}}
  labels:
    sts.silicom.com/svc: tsyncd
spec:
  type: NodePort
  selector:
    app: {{.Name}}-{{.NodeName}}
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: {{.Name}}-{{.NodeName}}
  name: {{.Name}}-{{.NodeName}}
  namespace: {{.Spec.Namespace}}
  annotations:
    openshift.io/scc: {{.Spec.Namespace}}
spec:
  selector:
    matchLabels:
      app: {{.Name}}-{{.NodeName}}
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app: {{.Name}}-{{.NodeName}}
    spec:
      shareProcessNamespace: true
      nodeName: {{.NodeName}}
      nodeSelector:
{{ range $k, $v := .Spec.NodeSelector }}
        {{ $k }}: "{{ $v }}"
{{ end }}
      serviceAccount: {{.Name}}
      hostNetwork: true
      containers:
      - image: {{.Spec.ImageRegistry}}/phc2sys:latest
        command: [ "/usr/bin/run-phc2sys.sh" ]
        name: {{.NodeName}}-phc2sys
        imagePullPolicy: Always
        network_mode: host
        env:
          - name: WAIT_FOR_GPS
{{- if .EnableGPS}}
            value: "true"
{{- else}}
            value: "false"
{{end}}
          - name: GPS_SERVER
            value: "0.0.0.0"
          - name: GPS_PORT
            value: "8888"
        volumeMounts:
          - name: devfs
            mountPath: /dev
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          capabilities:
            add:
            - CAP_SYS_TIME
      - image: {{.Spec.ImageRegistry}}/grpc-tsyncd:1.2.0.1
        imagePullPolicy: Always
        name: {{.NodeName}}-grpc-tsyncd
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          capabilities:
            add:
            - CAP_SYS_ADMIN
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 15
          periodSeconds: 30
        livenessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 60
          periodSeconds: 10
        ports:
        - containerPort: 50051
          name: {{.ServicePrefix}}-tsyncd
      - image: {{.Spec.ImageRegistry}}/siltsync:{{.Spec.StsVersion}}
        command: [ "/usr/bin/run-tsyncd.sh" ]
        imagePullPolicy: Always
        name: {{.NodeName}}-siltsync
        env:
          - name: WAIT_FOR_GPS
{{- if .EnableGPS}}
            value: "true"
{{- else}}
            value: "false"
{{- end}}
          - name: GPS_SERVER
            value: "0.0.0.0"
          - name: GPS_PORT
            value: "8888"
        args:
        - --zap-log-level=10
        volumeMounts:
          - name: devfs
            mountPath: /dev
          - name: {{.Name}}-siltsync-conf
            mountPath: /etc/tsyncd/tsyncd.conf
            subPath: tsyncd.conf
        securityContext:
          privileged: true
{{- if .EnableGPS }}
      - image: {{.Spec.ImageRegistry}}/siltsync:{{.Spec.StsVersion}}
        command: [ "/usr/bin/run-gpsd.sh" ]
        imagePullPolicy: Always
        name: {{.NodeName}}-gpsd
        readinessProbe:
          tcpSocket:
            port: 2947
          initialDelaySeconds: 15
          periodSeconds: 30
        livenessProbe:
          tcpSocket:
            port: 2947
          initialDelaySeconds: 60
          periodSeconds: 10
        ports:
        - containerPort: 2947
          name: {{.ServicePrefix}}-gpsd
        volumeMounts:
          - name: devfs
            mountPath: /dev
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          seLinuxOptions:
            level: "s0"
{{end}}
      volumes:
        - name: devfs
          hostPath:
            path: /dev
        - name: {{.Name}}-siltsync-conf
          configMap:
            defaultMode: 0777
            name: {{.Name}}-siltsync-conf
