name: Docker Image CI

on:
  push:
    branches:
    - master
    - 0.0.1
    - 0.0.1-dev
  pull_request:
    branches:
    - master
    - 0.0.1
    - 0.0.1-dev

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: fmt
      run: IS_CONTAINER=yes make fmt

    - name: Controller-gen
      run: make controller-gen

    - name: Build
      run: make all docker-build

